// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompteService.proto

package com.example.grpc3.stubs;

public interface GetTotalSoldeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetTotalSoldeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.SoldeStats stats = 1;</code>
   * @return Whether the stats field is set.
   */
  boolean hasStats();
  /**
   * <code>.SoldeStats stats = 1;</code>
   * @return The stats.
   */
  com.example.grpc3.stubs.SoldeStats getStats();
  /**
   * <code>.SoldeStats stats = 1;</code>
   */
  com.example.grpc3.stubs.SoldeStatsOrBuilder getStatsOrBuilder();
}
